AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Datasync Lambda

  Sample SAM Template for Datasync Lambda which start the tasks whenever any put action from s3 bucket

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Description: An AWS Serverless Specification template describing your function.
Resources:
  datasyncLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: datasync-lambda/
      MemorySize: 128
      



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  datasyncLambda:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt datasyncLambda.Arn
  datasyncLambdaIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt datasyncLambdaRole.Arn
