version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LarryClusterPlsRm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s9r9iavdtj35"
s3_prefix = "LarryClusterPlsRm"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
