AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  CopyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: gh-bip-apis
      StageName: v1
      Models:
         RequestClass :
           {
            "title": "RequestClass",
            "type": "object",
            "properties": {
                      "src": { "type": "string" },
                      "dest": { "type": "string" }   
                    }          
            }   
      Auth:
        #ApiKeyRequired: true
        DefaultAuthorizer: BIPLambdaRequestAuthorizer
        Authorizers: 
          BIPLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt BIPLambdaRequestAuthorizer.Arn
            Identity:
              Headers:
                - Authorization
          
  COPYFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'bip_api_copy'
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ./copyfunc
      Events:
        CopyAPI:
          Type: Api
          Properties:
            RestApiId: !Ref CopyApi
            Path: /copy #copy
            Method: POST
            RequestModel: 
              Model: RequestClass # REQUIRED; must match the name of a model defined in the Models property of the AWS::Serverless::API
              Required: true # OPTIONAL; boolean
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSSMFullAccess
      Timeout: 300  
      VpcConfig:
        SubnetIds: 
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id1:1}}'
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id2:1}}'
        SecurityGroupIds:
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/default_securitygroupid:1}}'

  GetStatusFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'bip_api_copystatus'
      Handler: handler.lambda_handler
      Runtime: python3.6
      CodeUri: ./getstatus
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSSMFullAccess
      Events:
        StatusAPI:
          Type: Api
          Properties:
            RestApiId: !Ref CopyApi
            Path: /copy/status
            Method: GET
            RequestParameters:
              - method.request.querystring.task_name:
                  Required: true
      Timeout: 300  
      VpcConfig:
        SubnetIds: 
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id1:1}}'
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id2:1}}'
        SecurityGroupIds:
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/default_securitygroupid:1}}'
              
  CancelTaskFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'bip_api_cancelcopy'
      Handler: handler.lambda_handler
      Runtime: python3.6
      CodeUri: ./cancelcopy
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AmazonSSMFullAccess
      Events:
        StatusAPI:
          Type: Api
          Properties:
            RestApiId: !Ref CopyApi
            Path: /copy/status
            Method: PUT
            RequestParameters:
              - method.request.querystring.task_name:
                  Required: true
              - method.request.querystring.status:
                  Required: true
      Timeout: 300  
      VpcConfig:
        SubnetIds: 
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id1:1}}'
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id2:1}}'
        SecurityGroupIds:
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/default_securitygroupid:1}}'
                       
  BIPLambdaRequestAuthorizer:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'bip_api_authorizer'
      CodeUri: ./authorizer
      Handler: copyAuthorizer.authorizer
      Runtime: python3.7
      Timeout: 120
      Policies:
      - AmazonS3ReadOnlyAccess
      - SecretsManagerReadWrite

  SchedulerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'bip_copy_scheduler'
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ./cronfunction
      Policies:
      - AWSLambdaVPCAccessExecutionRole
      - SecretsManagerReadWrite
      - AWSDataSyncFullAccess
      - AmazonSSMFullAccess
      - AmazonSNSFullAccess
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0/20 * * * ? *)
      Timeout: 600  
      VpcConfig:
        SubnetIds: 
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id1:1}}'
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/public_subnet_id2:1}}'
        SecurityGroupIds:
          - !Sub '{{resolve:ssm:/gh-bip/${AWS::Region}/default_securitygroupid:1}}'
                       

  FunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: FunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DeleteNetworkInterface'
                Resource: '*'
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref CopyApi

  ApiUrl:
    Description: "Copy API endpoint URL for v1 environment"
    Value: !Sub 'https://${CopyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/copy'
  
  StatusApiUrl:
    Description: "Get Status API endpoint URL for v1 environment"
    Value: !Sub 'https://${CopyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/copy/status'

  ControllerApiUrl:
    Description: "Control Copy status API endpoint URL for v1 environment"
    Value: !Sub 'https://${CopyApi}.execute-api.${AWS::Region}.amazonaws.com/v1/copy/status'
