AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UnitTestingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: unit_tests/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        UnitTesting:
          Type: Api
          Properties:
            Path: /test
            Method: get

Outputs:
  UnitTestingApi:
    Description: "API Gateway endpoint URL for Prod stage for Unit testing function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/test/"
  UnitTestingFunction:
    Description: "Unit Test Lambda Function ARN"
    Value: !GetAtt UnitTestingFunction.Arn
  UnitTestingFunctionIamRole:
    Description: "Implicit IAM Role created for Unit Testing function"
    Value: !GetAtt UnitTestingFunctionRole.Arn
